### PR TITLE
Update code maintainability

### PR DESCRIPTION
**Pull request by DevFelixDorn**
hello ! 
That's my really first PR so maybe i did wrong things, but i hope this will be helpful.
* added a php code sniffer 
* removed the array long syntax (less readable), 
* type hinted when an array is needed 
* added a @covers tag for every test (more understandable). 
* runned phpcbf so the code is PSR-2 compliant.

### CODE REVIEW

**Comment by koenpunt** [comment]
Hey @DevFelixDorn, thanks for taking the time to create this PR. Usually before submitting changes that completely change the source code, it's better to first open an issue to discuss the need for it.
That said, I don't have a strong opinion about these changes, so I let @dannyvankooten be the judge.

One thing that might be an issue; does the type annotations change the minimum supported php version?

**Comment by DevFelixDorn** [comment]
Well no! Because I type hinted only when it's an array and this is supported by php >=5.6.0. So there is no breaking changes.

**Comment by dannyvankooten** [comment]
Hey @DevFelixDorn,

Sorry for not merging this before. This is actually breaking the API contract for AltoRouter because the PHP requirement is actually 5.3+, crazy as it might be. That said, I think it is about time that AltoRouter is bumped to PHP version 5.6, so I'll go ahead and merge this right away.

**Comment by dannyvankooten** [comment]
Scratch that - type hints for arrays have been available since PHP 5.1 so looks like this isn't breaking the lib for PHP 5.3 at all.

**Pull request merged**
