### PR TITLE
Allow for optional parameters on bare/root url

### PR DESCRIPTION
**Pull request by koenpunt**
WIP fix for #98.

### CODE REVIEW

**Comment by mastacontrola** [comment]
I believe I found the problem for just a bare url not finding itself.

I've mimicked the code you've placed and found that the problem is in the "optional" regex generation code.

We end up with a regex of:
```
`^(?:/(?P<page>[0-9]++))?$`u
```

While this looks correct, it only assumes "optional" status as long as there is data present (it doesn't care what the data is, as long as something is there.

The regex should look like (I think):
```
`^(?:/(?P<page>[0-9]++)?)?$`u
```

The code that generates the regex for us should look like:
```
$pattern = '(?:'
    . ('' !== $pre ? $pre : null)
    . '('
    . ('' !== $param ? "?P<$param>" : null)
    . $type
    . ')'
    . ('' !== $optional ? '?' : null)
    . ')'
    . ('' !== $optional ? '?' : null);
```
At least this modification (specifically checking the internal grouping with an optional flag) seems to compile and test appropriately with your requested changes.

**Comment by koenpunt** [comment]
@mastacontrola thanks for the suggestion, I've put that in here 1cd027f

**Comment by koenpunt** [comment]
And it seems to work 🎉

**Comment by mastacontrola** [comment]
Glad I could help!

**Comment by mastacontrola** [comment]
Just updating for the issue referring to more or less the same issue.

I believe the issue was #98 which this should help fix.

**Comment by koenpunt** [comment]
@dannyvankooten do you got any remarks on this? I think it should be fine, since all the tests are passing. But I'm afraid for a potential regression...

**Comment by dannyvankooten** [comment]
If the tests pass then this should be good right? Otherwise we should really add a bunch of more tests. 

It's been a while since I looked at the AltoRouter regex generation but I'm going to take a look now, since it looks a bit overcomplicated to me right now... That's probably just me though. :smile:

**Comment by dannyvankooten** [comment]
Wouldn't it be better here to end up with a regex like this:

```
`^(?:/(?P<page>[0-9]++)?)$`u
```
This way, the part after the slash is truly optional but it still won't match on empty strings. I'm still trying to think of scenarios where this would have an effect, but I think that the latter `?` quantifier is not necessary anyway.

**Comment by dannyvankooten** [comment]
Never mind, the slash does indeed have to be optional too in case the optional part is not used in an URL part but as an extension or in with a part prefix. Thank god for tests. :smile:

**Comment by mastacontrola** [comment]
@dannyvankooten  @koenpunt If there's anything I can do to help you guys out just let me know.

If you're wondering why all of a sudden I'm "onboard" here it's because I'm using AltoRouter to help build my own API system for a project I've been working on and found that this fits really nicely for what I needed. So please don't take my constant updates/information as anything bad. Just trying to give back to you what you guys have enabled me to do.

**Comment by dannyvankooten** [comment]
Hey @mastacontrola,

Definitely appreciate you chiming in here, a lot! It's great to see some AltoRouter activity. 

We (or at least I) can be a little slow to respond but that's mostly because AltoRouter should be quite stable at this point. That's also why we're not super keen on breaking BC and like to keep AltoRouter the simple router that it is. I have yet to look at your PR though, just warning you how slow we can be so that you don't think it's because we're not interested or happy with your help. :smile:

**Comment by mastacontrola** [comment]
Well I recreated a Pull request with all the changes along with many joins of the other pr requests.

I know I need to label what is added and what pr it's working for, but I do understand if it is too much to go through.  From my testing, though, things appear to be working awesome (including all the changes you guys have been adding throughout the day.

**Pull request merged**
