### PR TITLE
Fix for optional parameters

### PR DESCRIPTION
**Pull request by dark-cms**
if first Paramter (found in Line 206) is optional strncmp should compare urllength without separator (cause preg_match works fine but strncmp returns -1)

### CODE REVIEW

**Comment by koenpunt** [comment]
Thanks for your contribution. Can you please add a test that demonstrates the faulty behavior?

**Comment by dark-cms** [comment]
Added a Test, based on my Problem,

The Router does not find a valid route, if only 1 dynamic Parameter is added.

My fix solved this, so

/users/dyn/[i:id]?

should work with /users/dyn and /users/dyn/1

on the other side

/users/dyn/[i:id]?/[see|follow:action]

seems not to work if url is /users/dyn/see

**Comment by koenpunt** [comment]
Closing since #99 got merged now

**Comment by mastacontrola** [comment]
If the url is to be optional shouldn't that include empty strings?

**Comment by mastacontrola** [comment]
What I mean at least is if you have a route of /[a:language]? Shouldn't it match either / or /en?

**Comment by koenpunt** [comment]
Yeah that should work. Or I don't understand your question?

**Comment by mastacontrola** [comment]
This was accidental placement of comment.  I saw the email about the "multi-optional" patch and when I commented I was on this posting rather than the PR #99

**Pull request closed without merging**
