### PR TITLE
Adding parameter transformers

### PR DESCRIPTION
**Pull request by mattsah**

### CODE REVIEW

**Comment by mastacontrola** [comment]
I've added this request to my fork of the repo in case you were worried about it being lost.

**Comment by mattsah** [comment]
@mastacontrola is your fork taking over as the official version behind the package?  We worked around it for the project we needed it on, but given that this was largely just ignored here, I'd likely not be inclined to use this router again unless it was being better supported.

**Comment by mastacontrola** [comment]
@mattsah My fork is not the "official" code but it is a fork, and I am almost constantly doing stuff with one of my other projects.

**Comment by mattsah** [comment]
@mastacontrola perhaps it would be worth making a package name adjustment in the composer/json -- even if it's just altorouter-plus or something.  Are you occasionally merging in upstream changes too?

**Comment by mastacontrola** [comment]
I am merging upstream.

**Comment by mattsah** [comment]
If that's the case then I'd definitely be inclined to use your version since it appears to be more open to useful feature enhancements, but the independent package name might help others to find it as well.

Does this also mean I can assume you're using the feature I added?  If so how did it work out for you?

**Comment by mattsah** [comment]
I'll use @mastacontrola's fork instead.

**Comment by mastacontrola** [comment]
Which feature? The transformers?  Yes it is included.

**Pull request closed without merging**
